apiVersion: v1
kind: Service
metadata:
  name: sample-linux-service
  namespace: demo-app-nginx
  labels:
    app: sample-linux-app
spec:
  selector:
    app: sample-linux-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
